### ISSUE TITLE
How to use zlib builder / release for zlib needed?

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#174]
My apologies if this is dumb, but: I noticed `Z/Zlib/build_tarballs.jl` here, which I could use. I am already using GMP, via https://github.com/JuliaPackaging/Yggdrasil/releases/download/GMP-v6.1.2-1/build_GMP.v6.1.2.jl -- so I thought I should be able to find a zlib build.jl in a similar place, i.e., under a tag `Zlib-*` or something. But as far as I can tell, there is no such tag or release. Maybe I am just missing it, or am misunderstanding something at a deeper level?

Any help would be appreciated!

**Comment by giordano** [comment]
It's not a dumb question: Yggdrasil is not providing `build.jl` scripts any more, as it's mainly targeting JLL packages that won't use those files.

For Zlib you can use this script: https://raw.githubusercontent.com/JuliaGraphics/Cairo.jl/master/deps/build_Zlib.v1.2.11.jl

> I am already using GMP, via https://github.com/JuliaPackaging/Yggdrasil/releases/download/GMP-v6.1.2-1/build_GMP.v6.1.2.jl

Are you using GMP for building a library?  I'm asking this because Julia already comes with GMP, so you don't need to install it on user's machine in a Julia package.

**Comment by fingolfin** [comment]
OK, good to know. It's a bit unclear for me from the outside what Yggdrasil is for and what not :-). Thanks for the int with zlib.

As to GMP: yes, I need to build further code which links against it, and also zlib. Actually, I also will (later on) need to link to mpfr, mpc, ntl, ZeroMQ and a bunch more.

**Comment by giordano** [comment]
> Actually, I also will (later on) need to link to mpfr, mpc, ntl, ZeroMQ and a bunch more.

Most of these are already here in Yggdrasil.  If you need help just ask :slightly_smiling_face:  BTW,
I'd recommend you contributing the builder to Yggdrasil :wink:

I'm going to close this ticket
