### ISSUE TITLE
GR_jll: fonts directory missing

### ISSUE THREAD

**Issue by jheinen** [JuliaPackaging/Yggdrasil#2447]
The `fonts` directory is missing in the `GR_jll` distribution.

Do we have to specify all the required files individually or is there a way to recursively add a directory (similar to `BinaryBuilderBase.FileSource`)?

**Comment by giordano** [comment]
All files that are in the `${prefix}` at the end of the build will be included in the tarball (excluding files coming from other dependencies, but I guess this shouldn't be the problem here).  Specifying file products with `FileSource` will only make sure that the files are present in the tarball (an error will be thrown otherwise), but it doesn't change the content of the tarball

**Comment by giordano** [comment]
Also, I do see the `fonts/` directory in https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.53.0%2B0/GR.v0.53.0.x86_64-linux-gnu-cxx11.tar.gz

**Comment by ViralBShah** [comment]
Is this fixed now?
