### ISSUE TITLE
ADIOS2 package not regenerated?

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#3088]
Two PR for ADIOS2 were merged yesterday in quick succession. I have the feeling that the second PR didn't lead to a new `ADIOS2_jll`.

How can I check this? I see that only one new version of `ADIOS2_jll` was published yesterday. Could it be that the second build was skipped since the first build was still active?

**Comment by giordano** [comment]
We're experiencing delays in getting PkgServer serving the latest version of registry, see #3074 #3079 #3087.  Yesterday I already tried to [re-launch the registration job](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=11300&view=results), but that doesn't help much, the problem is the registry not being updated.

**Comment by giordano** [comment]
The registry is back up now: https://github.com/JuliaRegistries/General/pull/37669
