### ISSUE TITLE
Packaging more CUDA/GPU libraries to be available through Yggdrasil/BB

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#3108]
It would be nice to be able to ship more CUDA compiled libraries through Yggdrasil. We have started wrapping a few, but there are some rough edges when it comes to dealing with cuda versions and such.

It would be nice to upgrade the Yggdrasil/BB capabilities so that we can ship these libraries just like everything else. I wasn't sure if we have a list of things that need to happen to make this possible, and hence starting this issue.

@staticfloat @maleadt @giordano

**Comment by giordano** [comment]
My understanding is that there are two big issues:

* Pkg can't deal with optional packages, or alternative packages, so most of the time we end up having `Library_jll` and `LibraryGPU_jll`/`LibraryCUDA_jll` and the users will need to choose to use one or the other
* `nvcc` is not a cross-compiler, so we can build CUDA-accelerated libraries only for `x86_64-linux-gnu`

**Comment by ViralBShah** [comment]
At least for the second point, starting with `x86_64-linux-gnu` is good enough for the foreseeable future. I suppose some folks may want it on Windows, although the bigger thing is probably GPU support on aarch64 linux that is shaping up based on Nvidia announcements.

**Comment by ViralBShah** [comment]
Isn't the big problem here also that you have to build against multiple CUDA versions?

**Comment by maleadt** [comment]
> Isn't the big problem here also that you have to build against multiple CUDA versions?

The build part is doable now: We put `cuda` in the triplet, and that way we can create a single package like https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl containing all the artifacts for all supported versions of CUDA. The build recipe can then just iterate the supported versions and augment the triplet: https://github.com/JuliaPackaging/Yggdrasil/blob/e5db27d5b53f6f19286f1288e26c2dec29603a7d/C/CUDNN/build_tarballs.jl#L52-L63

This currently only works for binary stuff though, because we haven't transformed CUDA_full_jll yet, and more importantly we haven't figured out the run-time part of this either (CUDA_full_jll is just `Pkg.add`ed as a regular dependency during build, so the JLLWrappers-based infrastructure needs to know how to select an appropriate CUDA artifact). @staticfloat's thought was to augment the host triplet with a CUDA tag, populated by the driver's CUDA version, but that only works for straightforward dependency resolution (e.g. your CUDA 11.3 driver can only use artifacts compiled against CUDA 11.3) while the actual compatibility scheme is more complicated (there's backwards compatibility, and starting with CUDA 11.2 limited semver-style forward compatibility).

**Comment by ViralBShah** [comment]
Wow those CUDNN binares are 700MB each!

**Comment by maleadt** [comment]
And that's compressed...

```
maleadt@cyclops ~$ ls -lah /home/maleadt/.julia/artifacts/793934d761bbcf52eb6fa268b61281fa8480d78f/lib*                                                                                                      
total 1.4G
-r-xr-xr-x 1 maleadt maleadt 124M Aug 23 05:32 libcudnn_adv_infer.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt  94M Aug 23 05:32 libcudnn_adv_train.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt 686M Aug 23 05:33 libcudnn_cnn_infer.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt  89M Aug 23 05:33 libcudnn_cnn_train.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt 368M Aug 23 05:33 libcudnn_ops_infer.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt  57M Aug 23 05:33 libcudnn_ops_train.so.8.2.2*
-r-xr-xr-x 1 maleadt maleadt 155K Aug 23 05:32 libcudnn.so.8.2.2*
```

**Comment by ViralBShah** [comment]
Ok - but this is because cudnn itself is massive, right? Otherwise, most cuda built libraries should be reasonable sizes, right?

**Comment by maleadt** [comment]
Correct, although it's possible there shouldn't be a need to statically link with CUDA so the resulting binaries should be acceptable.

**Comment by devmotion** [comment]
> Pkg can't deal with optional packages, or alternative packages, so most of the time we end up having `Library_jll` and `LibraryGPU_jll`/`LibraryCUDA_jll` and the users will need to choose to use one or the other

Is there any plan yet for how to solve this first point in @giordano's list above?

I came across this problem when dealing with XGBoost.jl recently: In newer releases, the binary is built with CUDA support which pulls in also all the binary CUDA dependencies. This is quite problematic when trying to include it in system images - their size blows up (and as far as I know, in our use case we have certain size constraints - but maybe there were even some constraints imposed by Julia itself?). These binary dependencies are pulled in even in recent releases in which CUDA itself was made a weak dependency. Hence initially I assumed one could built one XGBoost_jll without CUDA support and one, e.g. named XGBoost_CUDA_jll, with CUDA support (as done for some other binaries in Yggdrasil it seems). However, then one faces exactly the problem @giordano mentions above: How can one switch between both binaries and ideally completely avoid installing XGBoost_CUDA_jll when no GPU support is needed?
