### ISSUE TITLE
[julia] julia binaries for BB packages that need them as dependencies

### ISSUE THREAD

**Issue by jstrube** [JuliaPackaging/Yggdrasil#321]
As far as I understand, Cxx and CxxWrap need access to julia binaries at build time.
There is a build recipe here in Yggdrasil, but that doesn't work, because julia can't be cross-compiled.
There's also a repo to host binaries here: https://github.com/JuliaPackaging/JuliaBuilder, but that hasn't been updated with new binaries in a while, so @gnimuc forked it and put some newer binaries there https://github.com/Gnimuc/JuliaBuilder/releases.
The new BB can't use the build recipes as binary dependencies any more, so after a discussion on slack, I tried to create an Artifacts.toml by hand, PR is here: https://github.com/JuliaRegistries/General/pull/7030. It was closed without a suggestion for a better place to put the binaries.
All of that is a bit of a mess.
I think it would be good to have one canonical location for julia binaries so that they can be pulled in as binary dependencies by BB scripts. I've tried to collect the references to all of the relevant locations in this issue, hopefully that helps with retiring some of them.
cc @barche @giordano @staticfloat

**Comment by staticfloat** [comment]
I think we probably want to create something similar to [`CompilerSupportLibraries`](https://github.com/JuliaPackaging/Yggdrasil/blob/master/0_RootFS/CompilerSupportLibraries/build_tarballs.jl), where we have a JLL that contains things like the headers and libraries for Julia.

While in the case of CSL, it's mostly okay that depending on it downloads a second copy of e.g. `libgcc_s`, it's much less desirable here because `libjulia` is big, and it would be wasteful to spend time and effort downloading it.

@giordano I'm thinking perhaps we should add a way to specify that a dependency should not be tracked in the JLL package.  What do you think?

**Comment by barche** [comment]
> @giordano I'm thinking perhaps we should add a way to specify that a dependency should not be tracked in the JLL package. What do you think?

Maybe build-time vs runtime dependencies, much like Arch PKGBUILD files have?

**Comment by vchuravy** [comment]
Buildtime dependencies would be much appreciated, things like capnproto are
both like a library and a compiler that you use during building your
binaries.

**Comment by giordano** [comment]
Yes, build-time dependencies are a frequent need.

In #110 I initially did an (almost) native build for x86_64-linux-gnu separately, put in a tarball, and used that as additional source. In the end I managed to not use an external source.

Having a native build already available for bootstrap would also avoid the troubles we had in #319 when targeting macOS. I think Valentin is having similar problems for another package

**Comment by ViralBShah** [comment]
@chrisrackauckas was also asking for this.

**Comment by giordano** [comment]
The more I think about compile-time dependencies, the more I'm convinced that in most cases they can be regarded more as an additional source than as a regular dependency, i.e. like something that doesn't necessarily need to live in `${prefix}`: these compile-time dependencies are often utilities/programs that can be referenced with the absolute path and don't need to stay in `${bindir}`.

However there would probably be cases where they need to be treated as regular dependencies installed in `${prefix}`.

**Comment by ViralBShah** [comment]
I was hoping that this would enable us to be able to download Julia through the BB infrastructure for running stuff as well (not just compile-time). Like in JuliaCall (for R) or pyJulia.

**Comment by giordano** [comment]
> I was hoping that this would enable us to be able to download Julia through the BB infrastructure for running stuff as well (not just compile-time). Like in JuliaCall (for R) or pyJulia.

Yes, the build-time dependencies is an orthogonal, but somewhat connected, issue to this one.

**Comment by ViralBShah** [comment]
I am thinking that in our Julia buildbots, before we build the installers, we create a directory called `julia-<commit>`, which could be tarballed and uploaded for this purpose. From there on, the rest is perhaps straightforward.

**Comment by staticfloat** [comment]
I think build-time dependencies fall into two camps:

The first is programs/utilities that need to run in order to generate stuff during the build.  Things like `make`, `gcc`, `tblgen` (for LLVM), etc...  These I think Mosé is correct on in saying that we can treat them like "extra sources".  We already have people doing this and it is mostly working.

The second camp is dependencies that are (or will be) automatically shipped within Julia (e.g. `Julia_jll ,`OpenBLAS_jll`, `MbedTLS_jll`, `CompilerSupportLibraries_jll`, etc....).  Things that are already present, so we don't actually need to download or load them.   For this, I can see multiple ways of dealing with it (have Julia ship with some artifacts/JLLs implicitly present in the stdlib depot, have `Pkg` ignore certain blacklisted JLLs, have a way for BinaryBuilder to not emit a dependency in a JLL implicitly trusting that it will exist on this Julia version, etc....).

**Comment by ViralBShah** [comment]
Should we execute the first step of getting tarballs of Julia binaries on Mac and Windows while we figure out the rest? That seems like it should be pretty straightforward - but for the people who are familiar with the build systems. If someone can give me directions on how to do it, I'm happy to give it a shot as well.

**Comment by fingolfin** [comment]
I really also could use this (see also https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/511)

**Comment by fingolfin** [comment]
@ViralBShah that would be very good to have indeed. The macOS .dmg at least basically already contains everything one needs for a tarball; just that it's inside a .dmg (which is annoying to extract on any platform other than macOS), and there is "hidden" inside an `.app` bundle -- but that's just a directory, and one can find a regular Julia "tree" under `Julia.app/Contents/Resources/julia/`. So the code which generates this .dmg should be 99% of the work required to make a "regular" .tar.gz for macOS (basically: throw away the code which produces the .app wrapper and the `.dmg`). Well, except for the notarization (= asking Apple to sign executables to prevent recent macOS warnings from throwing up all kinds of walls before letting user's execute it) ... But AFAIK you can't notarize a .tar.gz anyway, though a .zip could be.  Then again, if the main purposes of this is for use in BinaryBuilder, then I suppose it's not so important, because there macOS 10.10 is used, and that doesn't require any of this.

I just had a look, and it seems the code in `contrib/mac/app/` in the Julia repository takes care of the dmg -- but none of it is needed for the purpose here. So it should indeed be easy to create such an archive.

Can't comment on Windows.

What about the other platforms which BinaryBuilder supports but for which there are no Julia binaries? E.g. AFAIK the "Generic" Linux binaries are for glibc; there are no Julia binaries for musl, are there? Also none for powepc. Admittedly all of these are somewhat exotic, but it sure would be nice to cover them, too.

**Comment by ViralBShah** [comment]
We have all the pieces. Getting them uploaded and released is the real issue. I suspect we'll need help from @dilumalthuge, @ararslan and @staticfloat

**Comment by giordano** [comment]
Fixed by #1048
