### ISSUE TITLE
Incompatible library version in GtkSourceView

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaPackaging/Yggdrasil#3213]
GtkSourceView stopped working on MacOS at some point (it used to work I think), I'm getting this error :

>Reason: Incompatible library version: libgtksourceview-4.0.dylib requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2405.0.0

https://travis-ci.com/github/JuliaGtk/GtkSourceWidget.jl/jobs/518622238#L475

Which is strange since Gtk here is at version 3.24.29. Maybe a version number is missing here ?

https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/GtkSourceView/build_tarballs.jl#L45

**Comment by giordano** [comment]
I'll have a look in the next days, but the error message looks absolutely bizarre: `GtkSourceView_jll` was built [back in 2019](https://github.com/JuliaPackaging/Yggdrasil/commit/22e93f596f7f601570ac999c91321f6982b14a6b) and never updated since then, so it isn't very clear how come it's requiring a version of libgtk more recent than the one we built [last month](https://github.com/JuliaPackaging/Yggdrasil/commit/7dd6ea15f65a7d0a484455eca684fc3da812606f#diff-7587d52874afa645ff7b77e87270e3ae18bd8cca9e36feba90dc6ed54a1bd88b), which is currently also the last stable Gtk at all in the 3.x series.

**Comment by giordano** [comment]
Well, it looks like there is something seriously messed up in Gtk:
```
mose@Moses-MacBook-Pro ~ % julia-16 -E 'using Pkg; Pkg.activate(mktempdir(); io=devnull); Pkg.add(io=devnull, name="GTK3_jll", version="3.24.11"); using GTK3_jll; strip(readlines(`otool -L $(libgtk3)`)[2])'
"@rpath/libgtk-3.0.dylib (compatibility version 2408.0.0, current version 2408.4.0)"
mose@Moses-MacBook-Pro ~ % julia-16 -E 'using Pkg; Pkg.activate(mktempdir(); io=devnull); Pkg.add(io=devnull, name="GTK3_jll", version="3.24.29"); using GTK3_jll; strip(readlines(`otool -L $(libgtk3)`)[2])'
"@rpath/libgtk-3.0.dylib (compatibility version 2405.0.0, current version 2405.25.0)"
```
Gtk 3.24.11 had a _larger_ compatibility version than 3.24.29.  This explains the error, it doesn't explain how the compat version goes backward... I can fix this in the registry for the time being

**Comment by giordano** [comment]
Ok, problem explained: we always used meson to build Gtk3, but they have a [track](https://gitlab.gnome.org/GNOME/gtk/-/commit/70c4b66d99f66b9da27ded63f2c26e3c13ce07f8) [record](https://gitlab.gnome.org/GNOME/gtk/-/issues/3927) in having this build system broken.  The compat version for macOS is set in meson with [`darwin_version`](https://gitlab.gnome.org/GNOME/gtk/-/blob/88730e81c155c004034bb73cd5634c88abfe8a5e/gtk/meson.build#L984), which ultimately depends on the variable [`gtk_interface_age`](https://gitlab.gnome.org/GNOME/gtk/-/blob/88730e81c155c004034bb73cd5634c88abfe8a5e/meson.build#L55).  The problem is that at some point, between v3.24.11 and v3.24.29 they realised that `gtk_interface_age` was set incorrectly, and then they [changed it](https://gitlab.gnome.org/GNOME/gtk/-/commit/00aaba4d5bd307b3c499437c2ada1914c0cd5345), but in a way that 3.24.11 appears to be more recent than 3.24.29.

Thanks @staticfloat for helping in debugging this!

**Comment by jonathanBieler** [comment]
Great, thanks.
