### ISSUE TITLE
Make Yggdrasil artifacts available in Pkg servers

### ISSUE THREAD

**Issue by melonedo** [JuliaPackaging/Yggdrasil#3853]
GitHub release of Yggdrasil is hosting a lot of binary products, which are also accessible as artifacts. However, based on my observation, some of these binary products are hosted in the Pkg server, while some are not. This makes installing them hard if GitHub is not easily accessible due to network conditions. 
Is it possible to host all of them in Pkg servers so that we can download them from the nearest Pkg server?

**Comment by giordano** [comment]
CC @staticfloat

**Comment by staticfloat** [comment]
@melonedo can you please give some examples of artifacts that are not properly mirrored within the Pkg servers?

**Comment by melonedo** [comment]
`Rootfs.v2021.7.13.x86_64-linux-musl.unpacked` for example, although I can not prove other artifacts are hosted.

**Comment by staticfloat** [comment]
After some tracking down, I have figured out this is because the storage server rejects the tarball as having the wrong treehash.  This is because the storage server uses `Tar.tree_hash()` to calculate treehashes without extacting onto disk, whereas Pkg uses `Pkg.GitTools.tree_hash()`, and the behavior differs when the tarball contains symlinks that point outside of the tarball, e.g. that tarball contains absolute symlinks such as `/etc/mtab -> /proc/mounts`, or `/etc/ssl/certs/ca-cert-ACCVRAIZ1.pem -> /usr/share/ca-certificates/mozilla/ACCVRAIZ1.crt`.

When generating the rootfs, we should have an absolute symlink -> relative symlink conversion pass [like we do for the other rootfs images](https://github.com/JuliaCI/rootfs-images/blob/523e43ddfc0514628debe633042f191f4aa9605f/src/build_img/common.jl#L1-L30) that we use in CI.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
