### ISSUE TITLE
[finufft_jll] Optimial microarchitecture not downloaded

### ISSUE THREAD

**Issue by ludvigak** [JuliaPackaging/Yggdrasil#4252]
We just added microarchitecture expansion to finufft_jll (#4249). However, when I try it out through FINUFFT.jll, it doesn't load the optimal artifact.

Specifically, it downloads `x86_64-linux-gnu-march+x86_64` even though my computer can use `x86_64-linux-gnu-march+avx2` (which is faster).

If I remove the x86_64 entry from Artifacts.toml, then it downloads the expected avx2 artifact and I get the expected speedup, so I know that it should work.
(ping @giordano)

**Comment by giordano** [comment]
CC @staticfloat

**Comment by giordano** [comment]
Ok, talking with Elliot, it turns out the download side of the microarchitecture stuff isn't there yet.  As I said, we haven't used it yet into the wild, so some things definitely need to be fleshed out.  The good news is that at least we download the generic binaries by default, which is...well... no worse than before :sweat_smile: 

We need to "augment the platform" with the information of the microarchitecture by setting the tag `p["march"] = first(host_isas[idx])`.  https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1128 is developing right now the mechanism to do the platform augementation.

For our own record, this is code to get the ISA label for the current CPU:
```julia
julia> using Base.BinaryPlatforms

julia> host_arch = arch(HostPlatform())
       host_isas = CPUID.ISAs_by_family[host_arch]
       idx = findlast(((name, isa),) -> isa <= CPUID.cpu_isa(), host_isas)
       first(host_isas[idx])
"haswell"
```

Unfortunately it'll take still some time to make this work, but it's definitely something we want to eventually use, since we already have the infrastructure to build different microarchitectures!

**Comment by ludvigak** [comment]
Great that you guys are working on it! We'll be ready to have it tested in the wild once you're done =)

**Comment by giordano** [comment]
It took us a few iterations and few mistakes in BinaryBuilder, but we should finally be there!  `]add finufft_jll` should get you the right binary for your microarchitecture.

**Comment by ludvigak** [comment]
I noticed that it currently works great, but only if I force it to use the yanked release of finufft_jll.
Was there an issue with the deployment on avx512 architectures? (Do note that there is no avx512 artifact, since the current compiler doesn't seem to do a great job of that architecture.)

**Comment by giordano** [comment]
> Was there an issue with the deployment on avx512 architectures? (Do note that there is no avx512 artifact, since the current compiler doesn't seem to do a great job of that architecture.)

Yes, the problem was that on AVX512 systems the choice of the artifact was falling back on the generic one, just because the package manager chooses the last artifact in the list, matching the architecture: the artifacts are currently written out sorted alphabetically, and so `x86_64` was the last one.  I was trying to do the same for #4675, but bumped into [other issues](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1193), to be addressed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1194 and https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/233, but the review of the latter required to do more changes, which unfortunately I don't have the time to do now 😞
