### ISSUE TITLE
[NetCDF_jll v400.802.102+0] default CA certificates for https connection

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaPackaging/Yggdrasil#4843]
NetCDF uses libcurl to make network connections.
In the new NetCDF_jll v400.802.102+0, it seems that no default CA certificates are not loaded which results in the following error when accessing a https URL:

```
Error:curl error: SSL peer certificate or SSH remote key was not OK
```

NetCDF can be configured via a configuration file to provide a path to the certificates and then the URLs can be load (which internally sets the libcurl option [CURLOPT_CAINFO](https://curl.se/libcurl/c/CURLOPT_CAINFO.html)). In the previous NetCDF_jll version this configuration step was not needed. I am wondering how it worked before and it is possible to restore the previous behavior. Unfortunately, NetCDF does not provide an API to set this file path at runtime (unlike GDAL as I learned).

If somebody can shed some light on the handling of the CA certificates in C libraries, this would be very helpful.

More info:
https://github.com/Alexander-Barth/NCDatasets.jl/issues/173

**Comment by visr** [comment]
Libcurl on Linux indeed seems not to be built with default CA certificates.

It can be set in the curl handle like so: https://github.com/JuliaWeb/LibCURL.jl/blob/ee2410eac254bb3dcd1b08414521ffbbfe118c93/README.md#ssl-certificates

If you use using `NetworkOptions.ca_roots()`, it will look in [different places](https://github.com/JuliaLang/NetworkOptions.jl/blob/4d3df6445bbca0556a7a9f2abb0e48ba7d774f5a/src/ca_roots.jl#L58-L68) until it finds them.

So with NetCDF the issue is that it uses libcurl under the hood and does not have a function to point libcurl to the `ca_roots()`. (It does through a config file but that has other downsides).

But rather than letting all users of libcurl set this path, would it be possible to have libcurl find the default CA certificates itself on Linux? I guess configuring the libcurl build with `--with-ca-bundle` gives issues since the path may be different at the user machines. Would there be other solutions? I see `--with-ca-fallback` exists.

https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibCURL/common.jl
https://stackoverflow.com/a/48434362

**Comment by Alexander-Barth** [comment]
Thanks @visr , we can close this here, I guess. Unfortunately, we needed to use a private API of NetCDF to implement this.
