### ISSUE TITLE
[xxHash_jll] Functions not exported on Windows builds

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPackaging/Yggdrasil#4945]
libxxhash.dll is built correctly for Windows by MSYS2: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-xxhash/PKGBUILD

I've tried moving `__declspec(dllexport)` outside any if-defs in #4941 , as well as removing the XXH_INLINE_ALL flag that would have disabled that; it "successfully" breaks non-Windows builds, but Windows builds still have no exports as reported by the `dumpbin /EXPORT` tool.

I'm going beyond my knowledge a bit here, not sure where else to go.

Cross-ref with xxHash issue: https://github.com/Cyan4973/xxHash/issues/715

**Comment by giordano** [comment]
I wouldn't expect using a different version of GCC having any effect on whether functions get exported or not (unless there are convoluted conditionals which are influenced by the version of the compiler).  We build vast majority of the software with GCC 4.8.5, for maximum compatibility.

**Comment by BioTurboNick** [comment]
Holy crap.

That last chunk, I think, was grabbing the static library `libxxhash.dll.a` and re-linking it into the DLL, overwriting the originally generated actual DLL.

**Comment by giordano** [comment]
For context, the original [`build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/3f170db5c4352ecba71e7dfabe96511bb2d82364/X/xxHash/build_tarballs.jl) for version [`v7.3`](https://github.com/Cyan4973/xxHash/releases/tag/v0.7.3) did ***not*** install the shared library for Windows, which was noted in https://github.com/Cyan4973/xxHash/issues/362 and later fixed by https://github.com/Cyan4973/xxHash/pull/363, which explains why nothing is necessary anymore to actually get the shared library into the tarball.

In the original recipe I hadn't noticed that the shared library was actually compiled but merely not installed, which would have avoid all issues.  However we have the problem that lots of packages don't build shared libraries for Windows because for whatever reason some people don't think that shared libraries aren't useful on Windows and they build only static libraries, so in many recipes we have to manually build a shared library out of a static library, which is what I attempted here except I mistook the import library as a static library (which is not, and that was also more than 2 years ago).

**Comment by BioTurboNick** [comment]
Ahh okay. Build systems are dark magic to me 😆
