### ISSUE TITLE
Why GDAL is not build with NetCDF+HDF dependencies?

### ISSUE THREAD

**Issue by joa-quim** [JuliaPackaging/Yggdrasil#4950]
Any particular reason, or just because no one had interest on it so far?

**Comment by visr** [comment]
There is no proper cross compilation support for those libraries, which is the reason that for instance we haven't been able to get a netCDF build for Windows in a while. See #4511.

There is interest in adding the netCDF drivers to GDAL, see https://github.com/JuliaGeo/GDAL.jl/issues/134. But I'd want to hold off until the issues with netCDF and HDF5 are resolved, since otherwise maintaining a cross platform GDAL build becomes really difficult.

**Comment by joa-quim** [comment]
Thanks. I've build GDAL with the HDF+netCDF versions mentioned in #4511 but with VisualStudio. Have not tried that build yet. I'll try to try them next week if time allows.

**Comment by ViralBShah** [comment]
HDF5 cross compilation woes: https://github.com/JuliaPackaging/Yggdrasil/pull/567
