### ISSUE TITLE
Hash mismatch on Bzip2 installation

### ISSUE THREAD

**Issue by ItIsI-Orient** [JuliaPackaging/Yggdrasil#5987]
Hi, I am trying to install [Bzip2_jll](https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl) version 1.0.8+0 (in hopes that it will be accepted as a dependency for Arrow 10.0.0+1), but I am running into a following error:
```
Error: Hash Mismatch!
   Expected sha256:   66ab5f13291739ee439e7b7a44f9c7ef16dcab2cbfa60e82dc9e2904b1f3549e
   Calculated sha256: 7cac890c49ed760223194100c84c701ecba65fcc2b0a8916950c19143c3bbddb
 @ Pkg.PlatformEngines /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/PlatformEngines.jl:629
ERROR: Unable to automatically install 'Bzip2' from '/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Circuitscape/5.11.2-Julia-1.7.2/packages/Bzip2_jll/Artifacts.toml'
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.PipeEndpoint)
    @ Pkg.Artifacts /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/Artifacts.jl:441
  [3] download_artifacts(env::Pkg.Types.EnvCache; platform::Base.BinaryPlatforms.Platform, julia_version::VersionNumber, verbose::Bool, io::Base.PipeEndpoint)
    @ Pkg.Operations /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:617
  [4] develop(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1201
  [5] develop(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; shared::Bool, preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.PipeEndpoint, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.PipeEndpoint}}})
    @ Pkg.API /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:215
  [6] develop(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.PipeEndpoint, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
  [7] develop(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
  [8] #develop#14
    @ /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
  [9] develop(pkg::Pkg.Types.PackageSpec)
    @ Pkg.API /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/Julia/1.7.2-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:141
 [10] top-level scope
    @ none:1
```
I have ran into this error already with [libpng_jll](https://github.com/JuliaBinaryWrappers/libpng_jll.jl) version 1.6.38+0 and solved it there by using an older version (v1.6.37+5), but this approach isn't suitable here, because Arrow requires version 1.0.8. Any kind of help would be appreciated!

**Comment by giordano** [comment]
As far as I can tell you're checking out this revision of Bzip2_jll: https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/blob/61c41bdc6d6c1e2304911099a5700e5909108bb6/Artifacts.toml#L117 which however is ***not*** registered because it was broken.

**Comment by ItIsI-Orient** [comment]
@giordano So what version am I supposed to use for Arrow to work properly? Using the previous version (1.0.7+0) doesn't work, since Arrow has a requirement for Bzip2 to be at least of version 1.0.8

**Comment by giordano** [comment]
The only registered `1.0.8+0`, there's no ambiguity: https://github.com/JuliaRegistries/General/blob/d18d9af535476cdaf9def043f9220f26f41f9fac/B/Bzip2_jll/Versions.toml#L22-L23

**Comment by boegel** [comment]
I had a quick chat with @giordano on this to clear up the confusion. Here's the summary:

* A while ago, there was a problem that caused incorrect tagging of versions (see https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/709). The problem was fixed (see https://github.com/JuliaPackaging/Yggdrasil/pull/2044), but the incorrect tags did not get cleaned up because it didn't affect the Julia package manager directly (which doesn't care about git tags at all);
* In case of `Bzip2_jll.jl`, the problem is similar (faulty tag), but the cause is different (quoting @giordano: "the problem is that we had an initial build of 1.0.8 which created the git tag, realised that it had problems, and then did a new build, which reused the existing git tag");
* So, the `Bzip2-v1.0.8+0` tag for `Bzip2_jll.jl` is currently pointing to the wrong commit ([61c41bd](https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/commit/61c41bd), it should be pointing to [aa035c3](https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/commit/aa035c3) instead. This can be figured out by looking at the [commit history in the `Bzip2_jll.jl` repo](https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/commits/main): the correct commit is the *most recent* commit that mentions `1.0.8+0`.

The problem with [`libpng_jll`](https://github.com/JuliaBinaryWrappers/libpng_jll.jl) is similar: the `libpng-v1.6.38+0` tag is currently on commit [b778f2a](https://github.com/JuliaBinaryWrappers/libpng_jll.jl/commit/b778f2a) while it should be on [7610368](https://github.com/JuliaBinaryWrappers/libpng_jll.jl/commit/7610368).

cc @ItIsI-Orient @lexming
