### ISSUE TITLE
Should we augment with CUDA only on x86_64-linux-gnu?

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#6911]
For reference see https://discourse.julialang.org/t/xgboost-libxgboost-not-defined-error/100542/10.  The problem is that the user has CUDA on a Windows machine, so `XGBoost_jll.host_platform` is `Windows x86_64 {cuda=12.1, cxxstring_abi=cxx11, julia_version=1.8.0, libgfortran_version=5.0.0}`, but the only Windows wrapper we have for XGBoost is [`x86_64-w64-mingw32-cuda+none`](https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/blob/main/src/wrappers/x86_64-w64-mingw32-cuda%2Bnone.jl).  I think that we should augment with CUDA tag only `x86_64-linux-gnu` (or at least set `cuda=none` everywhere else) since that's the only platform for which we can build binaries anyways?  Or maybe there are cases where this is useful?  If so, maybe this could be made optional depending on the case?

CC: @tylerjthomas9 @maleadt @vchuravy.

**Comment by vchuravy** [comment]
PPC/AArch64 are certainly other targets we can build binaries for.

**Comment by maleadt** [comment]
I guess the assumption is that JLLs should only use the CUDA tag for platforms where CUDA builds are supported (additionally providing a `cuda=none` build for fallback purposes).

What happens if we have both a `cuda=none` artifact and one with `cuda` set to a proper version string? Maybe we could change the comparison strategy so that we don't need `cuda=none`, which would make the whole deal simpler.

**Comment by maleadt** [comment]
Proposed API:

```julia
platforms = supported_platforms()
cuda_platforms = CUDA.supported_platforms()

for platform in [platforms; cuda_platforms]
    if platform in platforms && CUDA.is_supported(platform)
        platform["cuda"] = "none"
    end

    # ...
end
```
