### ISSUE TITLE
LLVM stack: Which archives to ship

### ISSUE THREAD

**Issue by Gnimuc** [JuliaPackaging/Yggdrasil#693]
as per reported in https://github.com/JuliaBinaryWrappers/Clang_jll.jl/issues/1.

**Comment by Gnimuc** [comment]
I'm not 100% sure whether there is a way to walk around this or not. I would be happy to know how to compile a library that only tweaks LLVM/Clang source code a bit in an efficient way without directly linking to those static libraries. :)

**Comment by vchuravy** [comment]
x-ref: https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/issues/4

Clang should be able to link against `libClang-cxx`, which we should be building everywhere, at least as of LLVM9.

But most likely we still need the compiler-rt archives.

In general I agree with @krrutkow that we shouldn't bundle the static libraries.
@staticfloat enabled them in https://github.com/JuliaPackaging/Yggdrasil/pull/640 since apparently `llvm-config` checks for them.

**Comment by Gnimuc** [comment]
Just tested on Julia 1.5, Cxx.jl can be successfully linked with `libclang-cpp`. Since `libclang-cpp` is only available in LLVM9+, we still need to ship static libraries if there is a plan to do the same reorg for LLVM8.
