### ISSUE TITLE
CXSparse build script missing variable

### ISSUE THREAD

**Issue by SteffenPL** [JuliaPackaging/Yggdrasil#7993]
Hi, 

I came across an error in this script:
https://github.com/JuliaPackaging/Yggdrasil/blob/7fc70cfcc358e06c2ac134c4ccadabb648743783/S/SuiteSparse/CXSparse/build_tarballs.jl#L38
The variable `version` is not defined and in general, it seems to lack an update to the `@v5` and `@v7` approach from `SuiteSparse_jll`. (On my machine, `using CXSparse_jll` also fails as `libsuitesparse.so.5` is not available (which makes sense as it pulls `SuiteSparse@v7`).

I'll probably try to fix that script, but don't know how fast I can do that. So, I thought of reporting here first.

**Comment by giordano** [comment]
That's because that recipe is including a file https://github.com/JuliaPackaging/Yggdrasil/blob/9fac7f1e2409b915fab1339330ae16b180e6ab2b/S/SuiteSparse/CXSparse/build_tarballs.jl#L1 which has changed since.  You may want to check out the repository at commit 9fac7f1e2409b915fab1339330ae16b180e6ab2b when the file you're looking at was last modified, so that you have a consistent state: https://github.com/JuliaPackaging/Yggdrasil/blob/9fac7f1e2409b915fab1339330ae16b180e6ab2b/S/SuiteSparse/common.jl
