### ISSUE TITLE
Clang_jll for Windows.

### ISSUE THREAD

**Issue by Thomas008** [JuliaPackaging/Yggdrasil#8906]
Already mentioned in #8015 , the clang in the artifacts of the package [Clang_jll ](https://github.com/JuliaBinaryWrappers/Clang_jll.jl) does not work for windows. Calling clang.exe there results in a windows error ("cannot find procedure entry point").
There are versions of clang that work fine in Windows.
Is it possible to incorporate such a clang version into Clang_jll?

**Comment by Thomas008** [comment]
Some versions that work in Windows, are e.g. at
[https://github.com/llvm/llvm-project/releases](https://github.com/llvm/llvm-project/releases)
and
[https://github.com/mstorsjo/llvm-mingw/releases](https://github.com/mstorsjo/llvm-mingw/releases)

**Comment by giordano** [comment]
I'm missing why opening this ticket: how's different from #8015?

**Comment by Thomas008** [comment]
This issue wants to be more specific, and calls for repairing the package Clang_jll.

**Comment by giordano** [comment]
I'm even more confused: isn't #8015 about Clang_jll too?

**Comment by Thomas008** [comment]
Yes, so far the problem is not solved? Do you have a suggestion?

**Comment by giordano** [comment]
Yes, I already gave them in https://github.com/JuliaPackaging/Yggdrasil/issues/8015#issuecomment-1912570921 and https://github.com/JuliaPackaging/Yggdrasil/issues/8015#issuecomment-1912766442.  Don't expect me to do anything on Windows, I don't use that system, I don't have any interest/time in doing anything for it.  I'm also going to close this ticket as duplicate because I still haven't got the point of keeping another one open.
