### ISSUE TITLE
CUDA_Driver_jll v0.10.2+0 Broken on System Images

### ISSUE THREAD

**Issue by BenCurran98** [JuliaPackaging/Yggdrasil#9462]
Hi, first of all, thanks for the package! 

I just noticed that CUDA_Driver_jll seems to have some weird issue when it's compiled onto a system image using [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) where Julia seems to chew up memory and then crash on launching. 

As a minimal example, you can set up a package with just CUDA_Driver_jll as a dependency and build the system image:
```julia
using Pkg
Pkg.generate("CudaTest")
Pkg.activate("CudaTest")
Pkg.add("CUDA_Driver_jll")

Pkg.activate(".")

Pkg.add("PackageCompiler")
using PackageCompiler

create_sysimage(["CudaTest"]; sysimage_path = "ExampleSysimage.so")
```

And then run

```bash
julia -JExampleSysimage.so
```

which eventually crashes.

I'm not sure if this is an issue with this package specifically or with PackageCompiler.jl, but figured I'd start the conversation here? 

I'm running on x86_64 with Ubuntu 24.04. If you need any more information please let me know :slightly_smiling_face: 

Thanks for your help!

**Comment by maleadt** [comment]
The problem is that CUDA_Driver_jll's `__init__` spawns a new process to check if the forwards compatible driver is loadable: https://github.com/JuliaPackaging/Yggdrasil/blob/4c2914b76eea6fd366766100b378b243794683be/C/CUDA/CUDA_Driver/init.jl#L75

When using a custom system image, that new process _also_ initialized `CUDA_Driver_jll`, leading to infinite recursion. One solution would be to filder out the `-JExampleSysimage.so` when spawning the subprocess, assuming that the regular system image would still be available. Another solution would be to define an env var to disable the initialization of CUDA_Driver_jll.

Would you be interested in creating a PR?

**Comment by BenCurran98** [comment]
Yep sure I'll have a crack :)

**Comment by BenCurran98** [comment]
I've made a PR following your suggestions [here](https://github.com/JuliaPackaging/Yggdrasil/pull/9553)

**Comment by BenCurran98** [comment]
Closing this now since [this fix](https://github.com/JuliaPackaging/Yggdrasil/pull/9553) got merged. Thanks for your help!
